---
title: "Unused Chunks"
output: html_notebook
---

```{r import data from XLSX workbooks}
paths <- Sys.glob("data/*.xlsx")
bind_data <- import_list(paths, rbind = TRUE)
bind_data <- as.data.frame(bind_data)
str(bind_data)
View(bind_data)
```

```{r list files in directory to be combined, message=FALSE, warning=FALSE, cache=TRUE}
files_xlsx <- fs::dir_ls(glob = "Tb-*xlsx") #list of xlsx files in current directory
files_xlsx
```

```{r convert files xlsx to csv, cache=TRUE}
#use `rio` to convert xlsx files to csv so `vroom` can combine them
#WARNING this takes a few minutes because of large file size##
xls <- dir(pattern = "xlsx")
created <- mapply(convert, xls, gsub("xlsx", "csv", xls))
```
Gather the files.
```{r data combine and import, message=FALSE, warning=FALSE, cache=TRUE, include=FALSE}
files <- fs::dir_ls(glob = "Tb-*csv")
data <- vroom(files,col_select = c(DateTime, Tb, ID, Population,file_name,sheet_name, notes, sample_int))
#doesn't read in date or time columns because of potential wonky AM-PM problem (rather than 24h time) in ibutton data
#calculate date, time, month, etc. from 'DateTime' field (which is properly formatted)

unlink("*csv") #removes all .csv files from directory to save space after importing (.csv files are huge)
```




```{r R-playground method}
#https://github.com/NiharikaGoel12/R-Playground
library(openxlsx)
path <- "data"
merge_file_name <- "data//merged_file.xlsx"

filenames_list <- list.files(path= path, full.names=TRUE)

All <- lapply(filenames_list,function(filename){
    print(paste("Merging",filename,sep = " "))
    read.xlsx(filename)
})

df <- do.call(rbind.data.frame, All)
write.xlsx(df,merge_file_name)
#does not preserve cell formatting when combining
```


```{r report of file information, echo=FALSE}
cbind(
  file.info(files)[,c("size"), drop=FALSE],
  x = as.character(file.mtime(files))) %>% 
  separate(x,
           into = c("DateModified","TimeModified"),
           sep=" ") %>% 
  tibble::rownames_to_column() %>% 
  select(FileName=rowname,
         FileSize=size,
         DateModified,
         TimeModified)
```